spring:
  config:
    import: optional:nacos:${spring.application.name}.${file-extension:yaml}

  application:
    name: content-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml

  datasource:
    url: jdbc:mysql://localhost:3306/content_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: content_service
    password: C0nt3ntSrv@2025!db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cache:
    type: redis

  messages:
    encoding: UTF-8
    basename: i18n/messages

server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: INFO
  file:
    name: ../logs/content-service-dev.log

seata:
  enabled: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
