server.shutdown=graceful

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=shutdown

management.endpoint.shutdown.access=unrestricted
management.endpoint.health.show-details=always
