server:
  port: 8080

spring:
  config:
    import: optional:nacos:${spring.application.name}.${file-extension:yaml}

  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/contents/**
          filters:
            - StripPrefix=2

      default-filters:
        - AddRequestHeader=X-Request-Gateway, gateway-service

logging:
  level:
    root: INFO
  file:
    name: ../logs/api-gateway-dev.log
