server:
  port: 9000

spring:
  config:
    import: optional:nacos:${spring.application.name}.${file-extension:yaml}

  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/contents/**
          filters:
            - StripPrefix=2
            - name: JwtToHeaderFilter
              args:
                userIdClaim: sub
                usernameClaim: preferred_username
                rolesClaim: realm_access.roles

      default-filters:
        - AddRequestHeader=X-Request-Gateway, gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://forumx-keycloak:8080/realms/forumx-realm
          jwk-set-uri: http://forumx-keycloak:8080/realms/forumx-realm/protocol/openid-connect/certs
      client:
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/keycloak
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://forumx-keycloak:8080/realms/forumx-realm
            user-name-attribute: preferred_username

logging:
  level:
    root: INFO
  file:
    name: ../logs/api-gateway-dev.log
