spring:
  config:
    import: optional:nacos:${spring.application.name}.${file-extension:yaml}

  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: public

  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: user_service
    password: U3er@2025!db
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  session:
    redis:
      flush-mode: ON_SAVE
      namespace: spring:session:userservice

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dlut.forumx.user.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8082
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: INFO
  file:
    name: ../logs/user-service-dev.log
