@host=http://localhost:8000/api
@version=HTTP/1.1
@type-json=Content-Type: application/json

POST {{host}}/users/register {{version}}
{{type-json}}

{
	"username": "ishio",
	"password": "aA!bb1111"
}

###
POST {{host}}/auth/login {{version}}
{{type-json}}

{
	"username": "ishio",
	"password": "aA!bb1111"
}

###
POST {{host}}/auth/logout {{version}}

###
POST {{host}}/actuator/shutdown {{version}}