@host=http://localhost:8000/api
@version=HTTP/1.1
@type-json=Content-Type: application/json

POST {{host}}/auth/register {{version}}
{{type-json}}

{
	"username": "ishioi",
	"password": "Aa1!bbbb"
}

###
POST {{host}}/auth/login {{version}}
{{type-json}}

{
	"username": "ishio",
	"password": "Aa1!bbbb"
}

###
POST {{host}}/auth/logout {{version}}
{{type-json}}


###
POST {{host}}/auth/guest {{version}}
{{type-json}}

###
{{host}}/boards

###
{{host}}/boards?q=A

###
{{host}}/boards?page=1&size=100

###
{{host}}/boards/1000000006

###
{{host}}/boards/1000000006/posts

###
{{host}}/boards/1000000006/posts/6

###
{{host}}/boards/1000000006/posts/6/comments

###
{{host}}/boards/1000000006/posts/6/comments/2

###
POST {{host}}/boards {{version}}
{{type-json}}

{
	"name": "你好",
	"description": "这是介绍",
	"moderatorUid": 1
}

###
PUT {{host}}/boards/1000000055 {{version}}
{{type-json}}

{
	"name": "你好呀",
	"description": "这是介绍喵！",
	"moderatorUid": 2
}

###
{{host}}/boards/1000000055

###
DELETE {{host}}/boards/1000000055 {{version}}