port 6379
daemonize no
pidfile /var/run/redis/redis-server.pid
logfile /var/log/redis/redis-server.log

save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"

maxmemory 256mb
maxmemory-policy allkeys-lru
